server:
  port: 0
spring:
  application:
    name: hello-service
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    service-url:
      #指定服务注册中心的地址（单节点）
      #defaultZone: http://localhost:1111/eureka
      #指定服务注册中心的地址（两个节点）
      defaultZone: http://peer1:1111/eureka,http://peer1:1112