server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CaiBaoHong/demo-spring-cloud/blob/dev/config # 配置文件所在的git仓库
#          search-paths: config # 查找配置文件的路径
          username: CaiBaoHong
          password: cbh@gh2016